import turtle
wn=turtle.Screen()
wn.bgcolor("red")
wn.title("Hello, Friend!")
def draw_square(t, sz):
    for i in range(4):
        tabby.forward(sz)
        tabby.left(90)
    tabby= turtle.Turtle()
    tabby.shape('turtle')
    tabby.color("yellow")
    tabby.pensize(3)
    draw_square(100, 20)
    tabby.hideturtle()
    tabby.penup()
    tabby.goto(-10, -10)
    tabby.showturtle()
    tabby.pendown()
    draw_square(120, 40)
    tabby.hideturtle()
    tabby.penup()
    tabby.goto(-20, -20)
    tabby.showturtle()
    tabby.pendown()
    draw_square(140, 60)
    tabby.hideturtle()
    tabby.penup()
    tabby.goto(-30, -30)
    tabby.showturtle()
    tabby.pendown()
    draw_square(160, 80)
    tabby.hideturtle()
    tabby.penup()
    tabby.goto(-40, -40)
    tabby.showturtle()
    tabby.pendown()
    draw_square(180, 100)
    tabby.hideturtle()
    wn.mainloop()